CREATE TABLE IF NOT EXISTS affiliate_settings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  default_commission_percent DECIMAL(5, 2) NOT NULL DEFAULT 25.00,
  settlement_day TINYINT NOT NULL DEFAULT 0,
  auto_settlement TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
