CREATE TABLE IF NOT EXISTS affiliate_profiles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  referral_code VARCHAR(20) NOT NULL,
  referred_by BIGINT NULL,
  commission_percent DECIMAL(5, 2) NOT NULL DEFAULT 25.00,
  status ENUM('pending', 'approved', 'rejected', 'blocked') NOT NULL DEFAULT 'pending',
  registered_as_affiliate TINYINT(1) NOT NULL DEFAULT 0,
  total_referrals INT NOT NULL DEFAULT 0,
  total_deposit DECIMAL(15, 2) NOT NULL DEFAULT 0,
  total_withdraw DECIMAL(15, 2) NOT NULL DEFAULT 0,
  total_turnover DECIMAL(15, 2) NOT NULL DEFAULT 0,
  total_profit_loss DECIMAL(15, 2) NOT NULL DEFAULT 0,
  total_commission DECIMAL(15, 2) NOT NULL DEFAULT 0,
  pending_commission DECIMAL(15, 2) NOT NULL DEFAULT 0,
  settled_commission DECIMAL(15, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_affiliate_profiles_user_id (user_id),
  UNIQUE KEY uq_affiliate_profiles_referral_code (referral_code),
  INDEX idx_affiliate_profiles_referred_by (referred_by),
  INDEX idx_affiliate_profiles_status (status),
  CONSTRAINT fk_affiliate_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_affiliate_profiles_referrer FOREIGN KEY (referred_by) REFERENCES affiliate_profiles(id) ON DELETE SET NULL
);
