CREATE TABLE IF NOT EXISTS bonus_user_progress (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  rule_id BIGINT NULL,
  deposit_transaction_id BIGINT NULL,
  deposit_amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
  bonus_percent DECIMAL(5, 2) NOT NULL DEFAULT 0,
  bonus_amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
  turnover_multiplier DECIMAL(8, 2) NOT NULL DEFAULT 1,
  required_turnover DECIMAL(15, 2) NOT NULL DEFAULT 0,
  completed_turnover DECIMAL(15, 2) NOT NULL DEFAULT 0,
  remaining_turnover DECIMAL(15, 2) NOT NULL DEFAULT 0,
  progress_percent DECIMAL(5, 2) NOT NULL DEFAULT 0,
  claim_count INT NOT NULL DEFAULT 1,
  status ENUM('in_progress', 'completed', 'claimed', 'expired', 'cancelled') NOT NULL DEFAULT 'in_progress',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_bonus_user_progress_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_bonus_user_progress_rule FOREIGN KEY (rule_id) REFERENCES bonus_turnover_rules(id) ON DELETE SET NULL,
  UNIQUE KEY uq_bonus_user_progress_deposit_tx (deposit_transaction_id),
  INDEX idx_bonus_user_progress_user_status (user_id, status),
  INDEX idx_bonus_user_progress_rule_id (rule_id),
  INDEX idx_bonus_user_progress_created_at (created_at)
);
