CREATE TABLE IF NOT EXISTS gaming_api_settings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  provider_name VARCHAR(120) NOT NULL DEFAULT '',
  api_mode ENUM('demo', 'production') NOT NULL DEFAULT 'demo',
  base_url VARCHAR(500) NOT NULL DEFAULT '',
  api_key VARCHAR(500) NOT NULL DEFAULT '',
  secret_key VARCHAR(500) NOT NULL DEFAULT '',
  operator_id VARCHAR(120) NOT NULL DEFAULT '',
  callback_url VARCHAR(500) NOT NULL DEFAULT '',
  webhook_secret VARCHAR(500) NOT NULL DEFAULT '',
  currency VARCHAR(10) NOT NULL DEFAULT 'BDT',
  is_active TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
