CREATE TABLE IF NOT EXISTS homepage_sliders (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(200) NULL DEFAULT NULL,
  image_url VARCHAR(500) NOT NULL,
  link_url VARCHAR(500) NULL DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_homepage_sliders_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
