CREATE TABLE IF NOT EXISTS winypay_payment_orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  transaction_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  order_type ENUM('deposit', 'withdraw') NOT NULL,
  order_id VARCHAR(100) NOT NULL,
  pay_type VARCHAR(30) NULL,
  amount DECIMAL(15, 2) NOT NULL,
  status ENUM('initiated', 'awaiting_callback', 'success', 'failed') NOT NULL DEFAULT 'initiated',
  internal_txn_id VARCHAR(120) NULL,
  gateway_transaction_id VARCHAR(120) NULL,
  pay_url TEXT NULL,
  api_response JSON NULL,
  callback_payload JSON NULL,
  callback_signature VARCHAR(255) NULL,
  callback_message VARCHAR(500) NULL,
  processed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_winypay_order_id (order_id),
  UNIQUE KEY uq_winypay_gateway_txn (gateway_transaction_id),
  INDEX idx_winypay_transaction (transaction_id),
  INDEX idx_winypay_user (user_id),
  INDEX idx_winypay_status (status),
  CONSTRAINT fk_winypay_orders_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
  CONSTRAINT fk_winypay_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
