import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('103.168.173.101', 22, 'root', 'Jowabuzz@12', timeout=30)
_,o,_=c.exec_command('sed -n "620,720p" /www/wwwroot/jowabuzz/backend/services/depositBonusService.js')
print(o.read().decode())
_,o,_=c.exec_command("mysql -uroot -p656940d50e847e3f jowabuzz -e \"SELECT * FROM user_bonus_accounts WHERE user_id=31\"")
print(o.read().decode())
_,o,_=c.exec_command("mysql -uroot -p656940d50e847e3f jowabuzz -e \"SELECT * FROM user_bonus_claims WHERE user_id=31 ORDER BY id DESC LIMIT 5\" 2>/dev/null")
print(o.read().decode())
c.close()
