import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('103.168.173.101', 22, 'root', 'Jowabuzz@12', timeout=30)
_, o, _ = c.exec_command('cat /www/wwwroot/jowabuzz/backend/controllers/siteGameController.js')
print(o.read().decode())
_, o, _ = c.exec_command('cat /www/wwwroot/jowabuzz/backend/routes/publicSiteGamesRoutes.js')
print(o.read().decode())
_, o, _ = c.exec_command('cat /www/wwwroot/jowabuzz/frontend/src/services/siteGameService.js')
print(o.read().decode())
c.close()
