import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('103.168.173.101', 22, 'root', 'Jowabuzz@12', timeout=30)
_, o, _ = c.exec_command("sed -n '246,280p' /www/wwwroot/jowabuzz/frontend/src/pages/profile/ProfileDepositPage.jsx")
print('UI submit:', o.read().decode())
_, o, _ = c.exec_command("sed -n '250,320p' /www/wwwroot/jowabuzz/backend/services/winypayService.js")
print('winypay:', o.read().decode())
_, o, _ = c.exec_command("mysql -uroot -p656940d50e847e3f jowabuzz -N -e \"SELECT provider, api_key FROM site_settings WHERE setting_key LIKE '%payment%' OR setting_key='general_payment_gateway' LIMIT 3\" 2>/dev/null; SELECT setting_key, setting_value FROM site_settings WHERE setting_key='general_payment_gateway'\"")
print('config:', o.read().decode())
c.close()
