import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('103.168.173.101', 22, 'root', 'Jowabuzz@12', timeout=30)
_, o, _ = c.exec_command("sed -n '713,770p' /www/wwwroot/jowabuzz/backend/services/depositBonusService.js")
print('=== applyDepositBonusTurnover ===')
print(o.read().decode())
_, o, _ = c.exec_command("sed -n '838,875p' /www/wwwroot/jowabuzz/backend/services/depositBonusService.js")
print('=== resolvePrimaryDepositBonusProgress ===')
print(o.read().decode())
_, o, _ = c.exec_command("grep -A6 'const requiredTurnover = Number(depositAmount' /www/wwwroot/jowabuzz/backend/services/depositBonusService.js | head -8")
print('=== new deposit turnover calc ===')
print(o.read().decode())
c.close()
