export {
  AFFILIATE_LOGO_SRC,
  canAccessPrivateAgent,
  canAccessPrivateAgent as canAccessAgentApp,
  getHostname,
  getLogoContext,
  getMainSiteFallbackPath,
  isAgentLandingRoute,
  isAgentLandingSiteHost,
  isAffiliateDashboardRoute,
  isAffiliateRoute,
  isAffiliateSiteHost,
  isJBCashAppSession,
  isMainSiteHost,
  isPrivateAgentRoute,
  isPrivateAgentRoute as isAgentAppRoute,
  isStandaloneDisplayMode,
  JBCASH_LOGO_SRC,
  MAIN_SITE_CANONICAL,
  MAIN_SITE_LOGO_FALLBACK,
  markJBCashAppSession,
  SITE_URLS,
} from './siteContext';
